### ISSUE TITLE
Bug in get_disks procedure on windows machine

### ISSUE THREAD

**Issue by ThePalm99** [WEEE-Open/pesto#44]
In Windows machines there are no mountpoints and the server raise an exception:
```
Exception while scanning for disks, skipping
Traceback (most recent call last):
  File "C:\Users\Lol\Desktop\WEEE-Open\pesto\basilico.py", line 868, in scan_for_disks
    disks[path] = Disk(disk_lsblk, TARALLO)
  File "C:\Users\Lol\Desktop\WEEE-Open\pesto\basilico.py", line 31, in __init__
    self._mountpoint_map = self._lsblk["mountpoint_map"]
KeyError: 'mountpoint_map'
Exception while scanning for disks, skipping
Traceback (most recent call last):
  File "C:\Users\Lol\Desktop\WEEE-Open\pesto\basilico.py", line 868, in scan_for_disks
    disks[path] = Disk(disk_lsblk, TARALLO)
  File "C:\Users\Lol\Desktop\WEEE-Open\pesto\basilico.py", line 31, in __init__
    self._mountpoint_map = self._lsblk["mountpoint_map"]
KeyError: 'mountpoint_map'

```
On windows machines it will be sufficient to send a mountpoint flag only in C: and asking for every drive if the user is sure to erase the device.

**Comment by lvps** [comment]
@ThePalm99 Between line 972 and 973, add:

else:
    result["mountpoint_map"] = {}
    result["mountpoint"] = []

It will be magically fixed, trust me bro, just trust me asd
(I didn't test the Windows part since I didn't have a Windows machine)
